In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

In [5]:
data = pd.read_csv("Weather Data.csv")
temp = pd
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [7]:
data["Temp_C"] = data["Temp_C"].astype(int)
data["Rel Hum_%"] = data["Rel Hum_%"].astype(int)
data["Temp_C"].dtypes == int

True

In [8]:
data.dtypes

Date/Time            object
Temp_C                int32
Dew Point Temp_C    float64
Rel Hum_%             int32
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [9]:
#Diviser les donnees train et test
Xtrain = pd.DataFrame(data[:5000],columns=['Dew Point Temp_C','Rel Hum_%','Wind Speed_km/h','Visibility_km','Press_kPa'])
Ytrain = pd.DataFrame(data[:5000],columns=['Temp_C'])
Xtest = pd.DataFrame(data[5000:],columns=['Dew Point Temp_C','Rel Hum_%','Wind Speed_km/h','Visibility_km','Press_kPa'])
Ytest = pd.DataFrame(data[5000:],columns=['Temp_C'])

In [12]:
reg = LinearRegression()
reg.fit(Xtrain,Ytrain)
reg.score(Xtest,Ytest)

0.9931106150986079

In [14]:
#Appliquer un modele knn  sur les donnees
from sklearn import neighbors
#transformer=StandardScaler()
model = neighbors.KNeighborsClassifier(n_neighbors=3)
np.ravel(Ytest)
np.ravel(Ytrain)
model.fit(Xtrain,Ytrain)
model.score(Xtest,Ytest)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


0.2124735729386892

In [20]:
def Temp(model,dew,hum,wind_speed,vis,press):
    x=np.array([dew,hum,wind_speed,vis,press]).reshape(1,5)
    #x=transformer.fit_transform(x)
    print(x)
    print("températeur = " , model.predict(x)[0])

In [16]:
data.head(1)

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0  1/1/2012 0:00      -1              -3.9         86                4   

   Visibility_km  Press_kPa Weather  
0            8.0     101.24     Fog

In [21]:
print(Temp(model,-3.9,86,4,8,101.24))

[[ -3.9   86.     4.     8.   101.24]]
températeur =  -1
None


C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [22]:
data.iloc[[4000]]

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
4000  6/15/2012 16:00      25               6.0         29               15   

      Visibility_km  Press_kPa Weather  
4000           48.3     102.08  Cloudy

In [23]:
print(Temp(model,6,29,15,48.3,102.08))

[[  6.    29.    15.    48.3  102.08]]
températeur =  25
None


C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [24]:
data.iloc[[6000]]

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
6000  9/7/2012 0:00      18              14.8         81                4   

      Visibility_km  Press_kPa Weather  
6000           24.1     100.62   Clear

In [25]:
print(Temp(model,14.8,81,4,24.1,100.62))

[[ 14.8   81.     4.    24.1  100.62]]
températeur =  19
None


C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
